create extension if not exists moddatetime schema extensions;

-- tables
create table projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null, 
  html text,
  css text,
  js text,
  is_private boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz  not null default now(),
  thumbnail_path text,
  thumbnail_url text
);

create trigger handle_updated_at before update on projects
  for each row execute procedure moddatetime(updated_at);

alter table projects enable row level security;

create policy "Anyone can read public projects"
on projects
for select
using (is_private = false);

create policy "Owners can read their own projects"
on projects
for select
using (auth.uid() = user_id);

create policy "Owners can insert their own projects"
on projects
for insert
with check (auth.uid() = user_id);

create policy "Owners can update their own projects"
on projects
for update
using (auth.uid() = user_id);

create policy "Owners can delete their own projects"
on projects
for delete
using (auth.uid() = user_id);

create table profiles (
  user_id uuid references auth.users(id) on delete cascade primary key,
  display_name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger handle_updated_at before update on profiles
  for each row execute procedure moddatetime(updated_at);

alter table profiles enable row level security;

create policy "Anyone can read profiles"
on profiles
for select
using (true);

create policy "Owners can insert their own profile"
on profiles
for insert
with check (auth.uid() = user_id);

create policy "Owners can update their own profile"
on profiles
for update
using (auth.uid() = user_id);

create policy "Owners can delete their own profile"
on profiles
for delete
using (auth.uid() = user_id);

-- supabase storage

insert into storage.buckets  (id, name, public)values  ('thumbnails', 'thumbnails', true);

CREATE POLICY "Authenticated users can upload files"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'thumbnails');

CREATE POLICY "Users can view own files"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'thumbnails');

CREATE POLICY "Users can delete own files"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'thumbnails'
  AND owner = auth.uid()
);

/*
-- Enable RLS
alter table storage.objects enable row level security;

-- Anyone (even anon) can view files
create policy "Anyone can view thumbnails"
on storage.objects
for select
using (bucket_id = 'thumbnails');

-- Authenticated users can upload
create policy "Authenticated users can upload thumbnails"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'thumbnails' and auth.uid() = owner);

-- Only owner can delete
create policy "Owners can delete thumbnails"
on storage.objects
for delete
using (bucket_id = 'thumbnails' and auth.uid() = owner);
*/